export const GET_PRODUCT_CATEGORY_MAIN_LIST = "GET_PRODUCT_CATEGORY_MAIN_LIST";
export const GET_PRODUCT_SUB_CATEGORY_MAIN_LIST = "GET_PRODUCT_SUB_CATEGORY_MAIN_LIST";
export const GET_PRODUCT_SUB_SUB_CATEGORY_MAIN_LIST = "GET_PRODUCT_SUB_SUB_CATEGORY_MAIN_LIST";
export const GET_CATEGORIES_FILTER_PRODUCT = "GET_CATEGORIES_FILTER_PRODUCT";
export const SUB_SUBCATEGORY_WISE_PRODUCT = "SUB_SUBCATEGORY_WISE_PRODUCT";

// my code

export const GET_CATEGORIES_PRODUCTS = "GET_CATEGORIES_PRODUCTS"
export const GET_SUB_CATEGORIES_PRODUCTS = "GET_SUB_CATEGORIES_PRODUCTS"
export const GET_SUB_SUB_CATEGORIES_PRODUCTS = "GET_SUB_SUB_CATEGORIES_PRODUCTS"


