export const TOGGLE_MODAL = "TOGGLE_MODAL"
export const TOGGLE_STORE_MODAL = "TOGGLE_STORE_MODAL"
export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL"
export const TOGGLE_FLOATING_CART = "TOGGLE_FLOATING_CART"

export const GET_DEVICE_INFO = "GET_DEVICE_INFO"