export const LOGIN_INPUT_CHANGE = "LOGIN_INPUT_CHANGE";
export const REGISTER_INPUT_CHANGE = "REGISTER_INPUT_CHANGE";
export const USER_REGISTRATION = "USER_REGISTRATION";
export const AUTH_LOGIN_CHECK = "AUTH_LOGIN_CHECK";
export const LOGOUT_USER = "LOGOUT_USER";