export const ADD_TO_WISH_LIST = "ADD_TO_WISH_LIST";
export const GET_USER_WISHLIST = "GET_USER_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const REMOVE_WISHLIST ="REMOVE_WISHLIST"